/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Test');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Test = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Test, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Test.displayName = 'proto.Test';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Test.prototype.toObject = function(opt_includeInstance) {
  return proto.Test.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Test} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Test.toObject = function(includeInstance, msg) {
  var f, obj = {
    testint: jspb.Message.getFieldWithDefault(msg, 1, 0),
    teststring: jspb.Message.getFieldWithDefault(msg, 2, ""),
    testdate: jspb.Message.getFieldWithDefault(msg, 3, ""),
    teststring2: jspb.Message.getFieldWithDefault(msg, 4, ""),
    testbool: jspb.Message.getFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Test}
 */
proto.Test.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Test;
  return proto.Test.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Test} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Test}
 */
proto.Test.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTestint(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeststring(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTestdate(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeststring2(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTestbool(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Test.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Test.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Test} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Test.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTestint();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTeststring();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTestdate();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTeststring2();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTestbool();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional int32 testint = 1;
 * @return {number}
 */
proto.Test.prototype.getTestint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.Test.prototype.setTestint = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string teststring = 2;
 * @return {string}
 */
proto.Test.prototype.getTeststring = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.Test.prototype.setTeststring = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string testdate = 3;
 * @return {string}
 */
proto.Test.prototype.getTestdate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.Test.prototype.setTestdate = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string teststring2 = 4;
 * @return {string}
 */
proto.Test.prototype.getTeststring2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.Test.prototype.setTeststring2 = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool testbool = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.Test.prototype.getTestbool = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.Test.prototype.setTestbool = function(value) {
  jspb.Message.setProto3BooleanField(this, 5, value);
};


